apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-deployment
  name: httpd-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-deployment
    spec:
      containers:
      - image: httpd:alpine3.19
        name: httpd
        resources: {}
status: {}
