apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-08-06T18:17:42Z"
  labels:
    app: mealie
  name: mealie
  namespace: mealie
  resourceVersion: "17424"
  uid: 03c843f4-38de-4b3a-a5c6-75066691b703
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
