apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v1.3.2
        name: mealie
        volumeMounts:
        - mountPath: "/app/data"
          name: mealie-data
        ports:
          - containerPort: 9000
        resources: {}
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
status: {}
